# Generated by Django 4.1 on 2023-01-24 07:41

from django.db import migrations, models
import django.db.models.deletion
import inventory.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attrName', models.CharField(default=None, max_length=50)),
                ('attrSVG', models.TextField(default=None, max_length=8000)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageName', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('imageActual', models.ImageField(blank=True, null=True, upload_to=inventory.models.upload_path)),
            ],
        ),
        migrations.CreateModel(
            name='ToolltipData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tooltipIframe', models.TextField(default=None, max_length=9000)),
                ('tooltipImage', models.ImageField(blank=True, default='settings.MEDIA_ROOT/logo.jpg', null=True, upload_to=inventory.models.upload_path2)),
                ('tooltipText', models.TextField(default=None, max_length=9000)),
                ('attributeName', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.inventoryattribute')),
            ],
        ),
        migrations.AddField(
            model_name='inventoryattribute',
            name='imageNameLink',
            field=models.ForeignKey( null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.inventoryitem'),
        ),
    ]
