# Generated by Django 4.1 on 2023-04-07 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_inventoryattribute_imagenamelink_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
