# Generated by Django 4.1 on 2023-04-18 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_passwordreset_user_inventoryitem_inventoruuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryitem',
            old_name='inventoruUser',
            new_name='inventoryUser',
        ),
    ]
