# Generated by Django 4.1 on 2023-04-18 05:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_rename_inventoruuser_inventoryitem_inventoryuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='inventoryUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
