# Generated by Django 4.1 on 2023-04-18 05:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_inventoryitem_inventoryuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryattribute',
            name='imageNameLink',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.inventoryitem'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='inventoryUser',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='toolltipdata',
            name='attributeName',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.inventoryattribute'),
        ),
    ]
