# Generated by Django 4.1 on 2023-05-14 04:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_inventoryitem_inventoryuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='inventoryUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
