# Generated by Django 4.1 on 2023-07-07 04:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import inventory.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_inventoryitem_inventoryuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='privacySetting',
            field=models.CharField(blank=True, default='Private', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='InventoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelName', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('privacySetting', models.CharField(blank=True, default='Private', max_length=50, null=True)),
                ('modelGLTF', models.ImageField(blank=True, null=True, upload_to=inventory.models.upload_path)),
                ('inventoryUserKey', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
