# Generated by Django 4.1 on 2023-07-21 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_inventoryitem_privacysetting_inventorymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='inventoryCategory',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='inventoryLocation',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
